'use strict';
const fs=require('fs');
const path=require('path');
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const html=fs.readFileSync('index.html','utf8');
const main=fs.readFileSync('main.js','utf8');
const storage=fs.readFileSync('storage-manager.js','utf8');
function assert(c,m){if(!c)throw new Error(m)}
assert(pkg.version==='4.1.1','package version mismatch');
assert(pkg.build?.productName==='Графикс','build.productName mismatch');
assert(pkg.build?.win?.icon==='assets/icon.ico','Windows icon is not configured');
assert(fs.existsSync('assets/icon.ico') && fs.existsSync('assets/icon.png'),'release icon assets missing');
assert(!fs.existsSync('assets/logo.png'),'obsolete built-in logo asset still exists');
assert(html.includes('src="assets/icon.png"'),'desktop app icon is not used by the UI');
assert(!html.includes('public-days') && !html.includes('g-days'),'weekday switcher markup/styles remain');
assert(!html.includes('data-public-day') && !html.includes('data-p=\"'),'weekday switcher handlers remain');
assert(storage.includes("STORAGE_VERSION = '4.1.0'"),'storage version mismatch');
assert(html.includes("const STORAGE_VERSION='4.1.0'"),'renderer storage version mismatch');
assert(pkg.build.files.includes('RELEASE_NOTES.md'),'current release notes are not packaged');
assert(pkg.build.files.includes('ai-service.js') && pkg.build.files.includes('ai-ui.js'),'AI runtime files are not packaged');
assert(main.includes("require('./ai-service')") && main.includes("ipcMain.handle('ai-status'") && main.includes("ipcMain.handle('ai-ask'"),'AI main-process IPC integration missing');
assert(fs.readFileSync('preload.js','utf8').includes('aiStatus:') && fs.readFileSync('preload.js','utf8').includes('aiAsk:'),'AI preload IPC integration missing');
assert(fs.readFileSync('ai-service.js','utf8').includes("openrouter/free") && fs.readFileSync('ai-service.js','utf8').includes('OPENROUTER_API_KEY'),'OpenRouter runtime configuration missing');
assert(fs.readFileSync('ai-ui.js','utf8').includes('AI-помощник'),'AI user interface missing');
assert(html.includes('startEditorColumnResize') && html.includes('startEditorRowResize'),'interactive print resize handlers missing');
assert(html.includes('resizeEditorColumnValue') && html.includes('resizeEditorRowValue'),'numeric print resize handlers missing');
assert(html.includes('await writer.write(new TextEncoder().encode(raw))'),'gzip stream write must be awaited');
assert(html.includes("typeof CompressionStream==='function'"),'CompressionStream capability check missing');
assert(html.includes('new TextEncoder().encode(raw)'),'UTF-8 Base64 fallback missing');
assert(html.includes("publicPeriod')?.addEventListener('change'"),'public period change handler missing');
assert(html.includes("publicFilters')?.addEventListener('change'"),'public filter change handler missing');
assert(html.includes('dashboard-month-grid') && html.includes('changeDashboardMonth'),'monthly dashboard calendar missing');
assert(html.includes('teacherUnavailableRowHtml') && html.includes('collectTeacherUnavailable'),'teacher availability editor missing');
assert(html.includes('teacherUnavailableConflict'),'teacher availability conflict check missing');
assert(html.includes('Педагог недоступен'),'teacher availability reporting missing');
assert(!/formatEnd\(x\)\)/.test(html),'broken formatEnd(x) call remains');
assert(/contextIsolation:\s*true/.test(main) && /nodeIntegration:\s*false/.test(main),'renderer isolation settings weakened');
assert(!/force-device-scale-factor/.test(main),'forced DPI scale remains');
assert(main.includes('requestSingleInstanceLock'),'single-instance protection missing');
assert(main.includes('setPermissionRequestHandler'),'permission request hardening missing');
assert(main.includes('MAX_IMPORT_FILE_BYTES = 50 * 1024 * 1024'),'import size guard missing');
assert(main.includes('stat.size > MAX_IMPORT_FILE_BYTES'),'file-size validation missing');
assert(main.includes("const allowed = `file://${path.join(__dirname, 'index.html')}`"),'navigation allowlist missing');
assert(html.includes('esc(x.resource)'),'conflict resource output must be escaped');
assert(!/AKIA[0-9A-Z]{16}/.test(main+html+storage),'possible AWS access key found');
assert(!/-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----/.test(main+html+storage),'private key material found');
for(const f of ['GRAFIX-4.1-FINAL-AUDIT.md','GRAFIX-4.1-USER-GUIDE.md','GRAFIX-4.1-ADMIN-GUIDE.md','GRAFIX-4.1-RELEASE-NOTES.md','GRAFIX-4.1-FINAL-ACCEPTANCE-MATRIX.md','FINAL_PRODUCT_DESCRIPTION.md','USER_GUIDE.md','ADMIN_GUIDE.md','DEVELOPER_GUIDE.md','SCHEDULING_ENGINE.md','AI_GUIDE.md','COMPETITOR_ANALYSIS.md','FINAL_AUDIT.md','CHANGELOG.md','RELEASE_NOTES.md'])assert(fs.existsSync(f),`missing documentation: ${f}`);

console.log('Release static checks passed.');
